marca = str(input("Digite a Marca do Carro: "))
placa = str(input("Digite placa do carro: "))
modelo = str(input("Digite o Modelo do Carro: "))
cor = str(input("Digite a cor do Carro: "))
print("A marca do carro é: \n",marca)
print("A placa do carro é: \n", placa)
print("O modelo do carro é: \n", modelo)
print("A cor do carro é: \n", cor)
