nome = str(input ("Digite o nome do aluno: "))
n1 = float(input("Digite a primeira nota: "))
n2  = float(input("Digite a segunda nota: "))
n3 = float(input("Digite a terceira nota: "))
n4 = float(input("Digite a quarta nota: "))
print("O nome do aluno é: \n", nome)
print("A primeira note é: \n", n1)
print("A segunda note é: \n", n2)
print("A terceira note é: \n", n3)
print("A quarta note é: \n", n4)
