nome = str(input ("Digite o seu nome: "))
idade = int(input ("Digite a sua idade: "))
sexo = str(input ("Digite o seu sexo: "))
endereco = str(input ("Digite o seu endereço: "))
fone = input ("Digite o seu telefone com DDD: ")
print('Meu nome é: \n', nome)
print('Minha idade é: \n', idade)
print('Meu gênero é: \n', sexo)
print('Meu endereço é: \n', endereco)
print('Meu telefone é: \n', fone)